AddFoodItem Use Case Implemented
samlukas/csc207proj pull request #18
Opened 2023-11-20 07:23 UTC by jinnyhaohao

For the state, I tried following the format for the get_recipe use case but is not sure whether the update state method is suppose to be used here. Additionally, the input data for the expiry date and amount are integers and floats respectively, and I was not sure if I was suppose to change those into strings.

2023-11-26 09:15 UTC, jheelee21 requested changes
Please have a look at my comments and let me know if you need anything from my delete food item use case!

2023-11-26 09:15 UTC, jheelee21 commented on src/interface_adapter/add_fooditem/AddFoodItemPresenter.java
> +        addFoodItemState.setFoodItemError(error);
You might want to check for specific errors like if the error is ingredient error OR moth error OR day error, ... from what you have for your AddFoodItemState instances and update the instances accordingly as all of the errors are instantiated as null in your state. If you're not sure about it, I can give you my DeleteFoodItemPresenter to look through as an example since our use cases are quite similar.

2023-11-26 09:15 UTC, jheelee21 commented on src/use_case/add_fooditem/AddFoodItemInteractor.java
> +            addFoodItemPresenter.prepareFailView("Something went wrong!");
One other point about your fail view and errors here! You have specific error cases as your state attributes but you are not really using every kind of error you declared there. Now I can only see two error cases. It might be better to reduce the number of error cases and make it more general so it is easier for you to implement those in your Interactor, or make the if statement here more specific to each error case.

2023-11-26 09:15 UTC, jheelee21 commented on src/interface_adapter/add_fooditem/AddFoodItemViewModel.java
> +        support.firePropertyChange("state", null, this.addFoodItemState);
Maybe change the state name as it might be confusing when all of the use cases come together in the main view.

2023-12-01 16:03 UTC, jinnyhaohao commented on src/view/GetRecipeView.java
> +//                getRecipeViewModel.firePropertyChange();
change so that property changes don't fire twice, only runs get recipes when there is no error
- Sam

2023-12-02 19:01 UTC, closed without merging